spring.application.name=ms-pedidos360-report

server.port=5000

spring.datasource.url=jdbc:postgresql://db-report.c540hhboaool.us-east-1.rds.amazonaws.com:5432/pedidos360_report

spring.datasource.username=postgres

spring.datasource.password=TU_CONTRASEÑA_DE_RDS

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true