spring.application.name=ms-pedidos360-report

server.port=5000

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/pedidos360_report}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:report_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:report_pass}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true